version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:371428523361:task-definition/susel-taskdef:2"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80