version: 0.2

env:
  variables:
    REPO              : "suselstar"
    ECR_REPO_NAME_1   : "nginx"
    ECR_IMAGE_TAG     : "latest"
    REGISTRY_URL      : "https://index.docker.io/v1/"

phases:
  install:
    commands:
      - echo "Check aws version"
      - aws --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - docker login $REGISTRY_URL -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME_1:$ECR_IMAGE_TAG -f ./dockerfile-nginx .
      - docker tag $ECR_REPO_NAME_1:$ECR_IMAGE_TAG $REPO/$ECR_REPO_NAME_1:$ECR_IMAGE_TAG
      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO/$ECR_REPO_NAME_1:$ECR_IMAGE_TAG
