version: "3"

services:
  nginx:
    image: suselstar/nginx_susel:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /output_logs:/volume
    networks:
      - SuselNetwork

  apache:
    image: suselstar/apache_susel:latest
    restart: always
    ports:
      - 8090:8090
    networks:
      - SuselNetwork

networks:
  SuselNetwork:
